version: "3"
services:
  minasbtc:
    build: .
    image: minasbtc:latest
    container_name: minasbtc-miner
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - CPU_THREADS=${CPU_THREADS}
      - POOL_URL=${POOL_URL}
    restart: unless-stopped